"""
Reason codes for FOUL-X M11.0 Red-Team Failure-Safety Harness.
"""

from enum import Enum


class RedTeamScenarioCode(str, Enum):
    """Deterministic scenario identifiers for Red-Team validation."""
    NORMAL_SUPPORTED_CONTROL = "NORMAL_SUPPORTED_CONTROL"
    MISSING_CRITICAL_MEASUREMENT = "MISSING_CRITICAL_MEASUREMENT"
    INVALID_SENSOR_VALUE = "INVALID_SENSOR_VALUE"
    THERMAL_PHYSICS_INCONSISTENCY = "THERMAL_PHYSICS_INCONSISTENCY"
    REGIME_SHIFT_OOD = "REGIME_SHIFT_OOD"
    INSUFFICIENT_FORECAST_HISTORY = "INSUFFICIENT_FORECAST_HISTORY"
    FORECAST_UNAVAILABLE = "FORECAST_UNAVAILABLE"
    MULTIPLE_SIMULTANEOUS_FAILURES = "MULTIPLE_SIMULTANEOUS_FAILURES"
    DETERMINISTIC_REPEATED_EXECUTION = "DETERMINISTIC_REPEATED_EXECUTION"
    SOURCE_DATA_IMMUTABILITY = "SOURCE_DATA_IMMUTABILITY"
